name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - bokeh
  - plotly
  - gdal
  - geopandas
  - rasterio
  - fiona
  - shapely
  - pyproj
  - pysal
  - geopy
  - geoviews
  - geoplot
  - dash
  - osmnx
  - networkx
  - cartopy
  - rtree
  - rsgislib
  - pyrosm
  - contextily
  - folium
  - mapclassify
  - matplotlib
  - scikit-learn
  - jupyterlab
  - jupytext
  - myst-nb
  - psycopg2